// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etbbjgxsmeineqeggpkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0YmJqZ3hzbWVpbmVxZWdncGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDcyNzIsImV4cCI6MjA2MDMyMzI3Mn0.syZ44aUtR2mqjw_II4Xh7m9Gqk0zCxT69xJYk1KXnl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);